### ISSUE TITLE
When will release the process of custom data?

### ISSUE THREAD

**Issue by GuoPingPan** [maeyounes/SparseCraft#3]
This is really a very practical work. When will the processing flow of custom data be released?

**Comment by maeyounes** [comment]
Hello,
thank you for your interest in this work. I just pushed the custom dataset preparation flow. 

I hope it serves your needs.

Kind regards,
MY

**Comment by GuoPingPan** [comment]
Thanks a lot!
But I encountered the below problem when I running with custom dataset.
Seem like the CUDA is lost but already install by me.
How can I deal with it.
```
/home/a4090/SparseCraft/datasets/colmap.py:62: UserWarning: Using torch.cross without specifying the dim arg is deprecated.
Please either pass the dim explicitly or simply use torch.linalg.cross.
The default value of dim will change to agree with that of linalg.cross in a future release. (Triggered internally at ../aten/src/ATen/native/Cross.cpp:62.)
  plane_eq, inliers = ground.fit(pts.numpy(), thresh=0.01) # TODO: determine thresh based on scene scale
Loaded point cloud from file containing 102458 points
cNumber of views for train split is 6
Number of views for valid split is 6
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name  | Type             | Params
-------------------------------------------
0 | model | SparseCraftModel | 22.9 M
-------------------------------------------
22.9 M    Trainable params
0         Non-trainable params
22.9 M    Total params
45.857    Total estimated model params size (MB)
Epoch 0: : 0it [00:00, ?it/s]
Update finite_difference_eps to 1.875 at step 0
NerfAcc: No CUDA toolkit found. NerfAcc will be disabled.
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/a4090/.local/lib/python3.8/site-packages/IPython/core/debugger.py", line 145, in BdbQuit_excepthook
    raise ValueError(
ValueError: `BdbQuit_excepthook` is deprecated since version 5.1

Original exception was:
Traceback (most recent call last):
  File "launch.py", line 160, in <module>
    main()
  File "launch.py", line 149, in main
    trainer.fit(system, datamodule=dm)
  File "/home/a4090/miniconda3/envs/copa/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 608, in fit
    call._call_and_handle_interrupt(
  File "/home/a4090/miniconda3/envs/copa/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/a4090/miniconda3/envs/copa/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/home/a4090/miniconda3/envs/copa/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1112, in _run
    results = self._run_stage()
  File "/home/a4090/miniconda3/envs/copa/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1191, in _run_stage
    self._run_train()
  File "/home/a4090/miniconda3/envs/copa/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1214, in _run_train
    self.fit_loop.run()
  File "/home/a4090/miniconda3/envs/copa/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/a4090/miniconda3/envs/copa/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 267, in advance
    self._outputs = self.epoch_loop.run(self._data_fetcher)
  File "/home/a4090/miniconda3/envs/copa/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/a4090/miniconda3/envs/copa/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 204, in advance
    response = self.trainer._call_lightning_module_hook("on_train_batch_start", batch, batch_idx)
  File "/home/a4090/miniconda3/envs/copa/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1356, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/home/a4090/SparseCraft/systems/base.py", line 62, in on_train_batch_start
    update_module_step(self.model, self.current_epoch, self.global_step)
  File "/home/a4090/SparseCraft/systems/utils.py", line 426, in update_module_step
    m.update_step(epoch, global_step)
  File "/home/a4090/SparseCraft/models/sparsecraft.py", line 113, in update_step
    self.occupancy_grid.every_n_step(
  File "/home/a4090/miniconda3/envs/copa/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/a4090/miniconda3/envs/copa/lib/python3.8/site-packages/nerfacc/grid.py", line 271, in every_n_step
    self._update(
  File "/home/a4090/miniconda3/envs/copa/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/a4090/miniconda3/envs/copa/lib/python3.8/site-packages/nerfacc/grid.py", line 224, in _update
    x = contract_inv(
  File "/home/a4090/miniconda3/envs/copa/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/a4090/miniconda3/envs/copa/lib/python3.8/site-packages/nerfacc/contraction.py", line 101, in contract_inv
    ctype = type.to_cpp_version()
  File "/home/a4090/miniconda3/envs/copa/lib/python3.8/site-packages/nerfacc/contraction.py", line 62, in to_cpp_version
    return _C.ContractionTypeGetter(self.value)
  File "/home/a4090/miniconda3/envs/copa/lib/python3.8/site-packages/nerfacc/cuda/__init__.py", line 13, in call_cuda
    return getattr(_C, name)(*args, **kwargs)
AttributeError: 'NoneType' object has no attribute 'ContractionType'
Epoch 0: : 0it [00:01, ?it/s]

```
